name: flacon-tabetai
version: '5.5.1'
summary: Flacon snap
description: |
  Flacon extracts individual tracks from one big audio file containing the entire album of music 
  and saves them as separate audio files.
grade: stable
confinement: strict

apps:
  flacon:
    command: desktop-launch flacon
    plugs: [unity7, x11, opengl, gsettings, home, removable-media, raw-usb, desktop-legacy, desktop]
    desktop: usr/share/applications/flacon.desktop
  
parts:
  flacon:
    source: https://github.com/flacon/flacon/archive/v5.5.1.tar.gz
    plugin: cmake
    build-packages:
           - g++
           - pkg-config
           - libqt5x11extras5-dev
           - qtbase5-dev
           - qttools5-dev
           - qttools5-dev-tools
           - libuchardet-dev
           - icu-devtools
    stage-packages:
           - dbus
           - libqt5x11extras5
           - qttranslations5-l10n
           - libflac8
           - libvorbisenc2
           - libflac++6v5
           - flac
           - wavpack
           - lame
           - libvorbis0a
           - libogg0
           - libopus0
           - vorbis-tools
           - opus-tools
           - vorbisgain
           - shntool
           - cuetools
           - python-mutagen
           - libxkbcommon0
           - libqt5core5a
           - libqt5gui5
           - libqt5widgets5
           - libqt5dbus5
           - libqt5svg5
           - libcanberra-gtk-module
           - ttf-ubuntu-font-family
           - fonts-dejavu
           - sox
    install: |
      sed -i 's|Icon=flacon|Icon=${SNAP}/share/icons/hicolor/512x512/apps/flacon.png|g' $SNAPCRAFT_PART_INSTALL/share/applications/flacon.desktop
    after: [desktop-qt5]
  
  faac:
     source: https://github.com/Arcen/faac.git
     plugin: autotools
  
  ttaenc:
    source: https://sourceforge.net/projects/tta/files/tta/ttaenc-src/ttaenc-3.4.1-src.tgz
    plugin: make
    artifacts: [ttaenc]
    organize:  
            ttaenc: bin/
  mp3gain:
    source: https://sourceforge.net/projects/mp3gain/files/mp3gain/1.5.2/mp3gain-1_5_2_r2-src.zip
    plugin: make
    artifacts: [mp3gain]
    organize: 
            mp3gain: bin/
  mac:
    source: https://github.com/fernandotcl/monkeys-audio.git
    plugin: cmake
